@include "hook-nodes.conf"

paths = (
    {
        in = "signal_node_sine"
        out = "file_node"

        hooks = (
            {
                type = "dp",
                enabled = true,
                priority = 88,
                signal = "sine",
                f0 = 50, # In Hz
                #dt = 0.01, # In seconds
                # Alternative to dt
                rate = 1000, # Hz
                harmonics = [ 0, 1, 3, 5, 7 ],
                inverse = false
            },
            {
                type = "limit_rate",
                enabled = true,
                mode = "origin", # "local" "received" "origin"
                priority = 89,
                rate = 200      # The maximum sample rate in 1/s before this hook will drop 
            },
            { 
                type = "print",
                enabled = true,
                priority = 90,
                format = {
                            type = "json"
                            indent = 0
                            compact = false
                            ts_received = true
                            ts_origin = true
                            offset = false
                            real_precision = 6
                            sequence = true
                        }
			}
        )
    }
)