# SPDX-FileCopyrightText: 2014-2023 Institute for Automation of Complex Power Systems, RWTH Aachen University
# SPDX-License-Identifier: Apache-2.0

# This files just contains some simple nodes
# which are used to demonstrate the functionalities
# of different hooks

nodes = {
    signal_node = {
        type = "signal"
        values = 5
        signal = "mixed"
    },
    signal_node_sine = {
        type = "signal.v2",
        format = {
                        type = "json",
                        indent = 0,
                        compact = false,
                        ensure_ascii = true,
                        escape_slash = false,
                        ts_received = true,
                        ts_origin = true,
                        offset = true,
                        real_precision = 6,
                        sequence = true
        },
        rate = 1000.0,              # fc in Hz, how many samples to emit per second
        realtime = false,            # Wait between emitting each sample
        limit = 1000,               # Only emit 1000 samples, then stop
        monitor_missed = true,      # Count and warn about missed steps
        in = {
            signals = (
                { name = "signal",   signal = "sine", type = "float",  amplitude = 230.00, frequency = 50, offset = 0.0   }
            )           
        }
    },
    file_node = {
        type = "file"
        uri = "/logs/log_signal_hook_%Y-%m-%d_%H-%M-%S.log",
    }
}