# This file represents a Workbench entity in the DESF framework
services:
  # Laboratory
  villas_hook_dp:
    profiles:
      - dp
    labels:
      desf.workbench: "Test DP hook"
    extends:
      file: ./dp/docker-compose.yaml
      service: villas_hook_dp
    networks:
      - simulation_shared_network
    
# Define all networks
networks:
  simulation_shared_network:
    driver: bridge
    labels:
      desf.entity.type: "WorkbenchNetwork"
      desf.description: "Shared network for inter-laboratory communication"
