# This file represents a Laboratory entity in the DESF framework
services:

  villas_hook_limit_rate:
    labels:
      desf.entity.type: "CommunicationNode"
      desf.entity.description: "Docker container running Villas Node for network communication"
      desf.laboratory: "Laboratory A"
    image: registry.git.rwth-aachen.de/acs/public/villas/node
    volumes:
      - ./config:/config
      - ./logs:/logs
    tty: true
    entrypoint: ["sh"]
    command: ["-c", "villas-node /config/limit_rate.conf"]
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
