# File di configurazione per Daemon su nodo villas UNIVERSITA VANVITELLI 

@include "node.conf"

paths = (
	{
		in  = [ "signal_node" ], 
        out = [ "nodo_villas_lab_a","file_json","file_json_compact","file_json_compact_no_ts" ],
        reverse = false,
        enabled = true,
        original_sequence_no = true,
        hooks = ( 
            {
                type = "limit_rate",
                enabled = true,
                mode = "received",
                priority = 90,
                rate = 100
            },
            {
                type = "dp"
                enabled = true
                signal = "sine"
                f0 = 50 # In Hz
                #dt = 0.02 # In seconds
                # Alternative to dt
                rate = 1000 # In Hz
                harmonics = [ 0, 1, 3]
                inverse = false
            },
            { 
            type = "print",
			enabled = true,
			format = {
                        type = "json"
                        indent = 0
                        compact = false
                        ts_received = true
                        ts_origin = true
                        offset = false
                        real_precision = 6
                        sequence = true
                    }
			}),
	}
)